import errno


try:
    recovery = open("recovery.txt", "r")
except FileNotFoundError:
    print("NOT FOUND")
